### ISSUE TITLE
Ic2-Classic

### ISSUE THREAD

**Issue by CubeWrench202** [F32Organization/Faithful32-1.7.10#39]
There is a port of the original industrialcraft2  to 1.7.10 by immibis
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10313&pageNo=1
This is a port of the 1.4.7 IC2,i find a resourcepack for that version but doesn't seems to work, a port of that Resourcepack to the new version should help,if someone know how to make it,please tell me and i will do it.

**Comment by Evolution0** [comment]
I'll be taking this on since work seemed to have stopped 5 months ago (and is in an incorrect file structure), shouldn't interfere with my RFTools work as most of the textures already exist and its a fairly small undertaking.

I am however redoing some of them as I didn't really like the look of them and recreating others (Like the missing Hazmat suit which I already have mostly done :D)

**Comment by Speiger** [comment]
Even if it is based on Immibis version there is now a IC2 Classic out which is more compatible with Exp addons and seem to get more popular...
Just to say right away i am maintaining that version of IC2 Classic.
Would be  cool if you could support that too. 
Little info: The textures from classic do not interfere with those from Exp, so it is possible to support both at once

**Comment by Xen1290** [comment]
@Speiger I'm doing this right now. I'm the guy  that asked you about GUI path

**Comment by Speiger** [comment]
oh ok. ^^" Sry

**Comment by Xen1290** [comment]
No problems, sorry for possible english mistakes

**Comment by DZCreeper** [comment]
IC2 Classic support will come when #476 is merged, closing this now.
