### ISSUE TITLE
Glass icons invisibility

### ISSUE THREAD

**Issue by Ugachaga** [F32Organization/Faithful32-1.7.10#396]
Glass icons becomes almost invisible when I use Faithful32.

Vanilla:
![glass_vanila](https://cloud.githubusercontent.com/assets/12869346/8715445/efbf77be-2ba3-11e5-8e06-ab32e9059495.jpg)

F32ME:
![glass_f32me](https://cloud.githubusercontent.com/assets/12869346/8715451/fd2453a2-2ba3-11e5-9177-88b83c9325e6.jpg)

From left to right: minecraft glass, enderio fused quartz, enderio quite clear glass, ic2 reinforced glass, bluepower sapphire glass, chisel2 bubble glass.

Problem concerns only icons, blocks are displayed as intended.

Minecraft 1.7.10
Modpack Infitech2 3.1.3
Optifine 1.7.10 HD U C1

**Comment by Evolution0** [comment]
This is due to texture filtering/mipmapping. Try disabling it.

Nothing that can be fixed on this end.

You will get the same issue with most texture packs as long as they use transparent textures with fine (1-2px) details and it gets worse as the resolution increases. (as you can see even vanilla glass has bits missing)

You might be wondering "But why is the IC2 and Bluepower glass fine?" again the fine details issue, those two use thicker lines than the rest.

**Comment by Xen1290** [comment]
https://github.com/F32Organization/Faithful32-1.7.10/issues/120

**Comment by Iclario** [comment]
Duplicate issue
