### ISSUE TITLE
Texture atlases in for Reika's stuff are corrupt

### ISSUE THREAD

**Issue by steveowashere** [F32Organization/Faithful32-1.7.10#458]
I just noticed the other day that the texture atlases for Reika's (/Reika/RotaryCraft/Textures/Items)
stuff are corrupt: 
![corrupt](https://cloud.githubusercontent.com/assets/13194819/9898611/e53ad19a-5c53-11e5-8e42-87df31c5af6f.PNG)

Original:
![org](https://cloud.githubusercontent.com/assets/13194819/9898615/eba352a0-5c53-11e5-939e-cdf669b78b9b.PNG)

I guess they'll need to be redone sometime, unless someone knows how to fix the atlas somehow?

**Comment by Evolution0** [comment]
Not corrupt exactly, its due to it being converted to something like PNG8 and not having enough colors left in the index to go around. 

And looking at the commit history it seems its my fault actually as I export pretty much all my textures in PNG8 and while that is perfectly fine for individual textures I must have had a brain fart in this instance as there is far too many colors in that image to be using and indexed color format like PNG8 :disappointed: 

Someone with the proper permissions need only do: 
`git revert 22b200a8bbeb4f65d4fdfdfb629b4d5f7f101092`

To get the original partially completed version back.

**Comment by steveowashere** [comment]
Ah okay, should be an easy fix then. I guess I'll wait until the change is reverted to start work on the atlas. 
What software do you use to save in PNG8? I use GIMP (I prefer it over PS for pixel work), but it lacks decent PNG saving options.

**Comment by Adaptivity** [comment]
@Evolution0 Github has revert button for years :smile:

**Comment by Evolution0** [comment]
I don't have write access @Adaptivity and have always used the terminal to manage repos haha

@steveowashere PS. Since I use it for everything else it was only natural for me, doing pixel work in PS takes some configuration to make comfortable though yes.

**Comment by steveowashere** [comment]
I guess i'll have to break down and start using PS... grumble grumble...

**Comment by Adaptivity** [comment]
@Evolution0 you don't need a write access. Simply go to merged PR and find revert button at the bottom.
![dfasdsadasd](https://cloud.githubusercontent.com/assets/1560181/9975824/d68fa508-5ed3-11e5-94a1-1dd8b85f20b9.jpg)
